---
# Source: vault-cluster/templates/configmap/server-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true # Be sure mlock syscall is available. If set to false prevent memory from being swapped to disk.
    ui = true

    default_max_request_duration = 30s


    listener "tcp" {
      tls_disable     = 1
      address         = "[::]:8200"
      cluster_address = "[::]:8201"
    }


    storage "raft" {
      path = "/vault/data"

      retry_join {
            leader_api_addr = "http://vault-0.vault-internal:8200"
      }

      retry_join {
            leader_api_addr = "http://vault-1.vault-internal:8200"
      }

      retry_join {
            leader_api_addr = "http://vault-2.vault-internal:8200"
      }

      retry_join {
            leader_api_addr = "http://vault-3.vault-internal:8200"
      }

      retry_join {
            leader_api_addr = "http://vault-4.vault-internal:8200"
      }
    }

    service_registration "kubernetes" {}
