apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vault
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  maxUnavailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      app.kubernetes.io/instance: vault
      component: server
