# Service for active Vault pod
apiVersion: v1
kind: Service
metadata:
  name: vault-active
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
{{ if eq .Values.ingress.enable false }}
  type: LoadBalancer
{{ end }}
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    component: server
    vault-active: "true"
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
