---
# Source: vault-agent-injector/templates/rolebinding/agent-injector.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-agent-injector-leader-elector-binding
  namespace: default
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-agent-injector-leader-elector-role
subjects:
- kind: ServiceAccount
  name: vault-agent-injector
  namespace: default
