---
# Source: vault-cluster/templates/rolebinding/server-discovery.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-discovery-rolebinding
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: vault-discovery-role
subjects:
- kind: ServiceAccount
  name: vault
  namespace: vault
