namespace: vault

ingress:
  enable: false
  host: vault.cluster.com

log:
  level: debug
  format: standard

server:
  maxRequestDuration: 30s
  replicas: 5 # The Vault Reference Architecture recommends a 5 node cluster to ensure a minimum failure tolerance of at least 2.
  setresources: false
  resources:
    cpu: 2
    memory: 8Gi
  version: "1.13.1"

storage:
  enable: false
  className: standard-rwo
  size: 100Gi
