apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'vault-agent-injector'
        # Should be removed when ingress is configured
        vault.hashicorp.com/tls-skip-verify: 'true'
        # vault.hashicorp.com/ca-cert: /vault/tls/vault.ca
        # vault.hashicorp.com/tls-secret: vault-ca
        vault.hashicorp.com/agent-inject-secret-env: 'demo'
        vault.hashicorp.com/agent-inject-template-env: |
          {{ with secret "demo/dummy" }}
            {{ range $key, $value := .Data.data }}
              export {{ $key }}="{{ $value }}"
            {{- end }}
          {{- end }}
    spec:
      serviceAccountName: vault-agent-injector
      containers:
        - name: demo
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh",  "-c", "source /vault/secrets/env && env | grep DEMO_SECRET && sleep infinity"]
